- name: Creating instance
  hosts: local
  connection: local
  vars:
    sub_id: subnet-069451d6f9f457b0f
    instances:
      - mysql
      - frontend
      - db
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0ba0f85038d861a18
    zone: quickbyte.online
  tasks: 
  - name: creating ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{sub_id}}"
      instance_type: t2.micro
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: Ec2_instances    # 1. time boto core boto3 error 2. aws authendication issue 3. aws authendication error
  - name: print 
    ansible.builtin.debug:
      msg: "{{Ec2_instances}}"
  - name: route 53
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: {{item.instances[0].private_ip_address}}
      wait: true
      overwrite: true

    loop: {{Ec2_instances.results}}
